Vagrant.configure("2") do |config|

  config.vm.define :rpmbuilder do |rpmbuilder|
    rpmbuilder.vm.box = "rpmbuild-centos64"
    rpmbuilder.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
    rpmbuilder.vm.network :private_network, ip: "192.168.50.10"
    rpmbuilder.vm.provision :puppet do |puppet|
      puppet.module_path    = "."
      puppet.manifests_path = "."
      puppet.manifest_file  = "rpmbuilder.pp"
    end
  end
end
